version: '2'

services:

  # load balancer

  nginx:
    image: gcr.io/ownersearch/nginx
    restart: always
    labels:
      role: nginx
    ports:
      - 80:80

  # microservices

  api:
    image: gcr.io/ownersearch/api
    restart: always
    environment:
      NODE_ENV: production
    labels:
      role: api

  website:
    image: gcr.io/ownersearch/website-server
    restart: always
    environment:
      NODE_ENV: production
    labels:
      role: website
