apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/ownersearch/nginx:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: wss
          containerPort: 8443
