apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: website
        keel.observer/policy: all
    spec:
      containers:
      - name: website
        image: gcr.io/ownersearch-176101/website-server:latest
        ports:
        - name: website
          containerPort: 3080
